name: .NET Test

on:
  push:
    branches: [ "main" ]
  pull_request_target:  # Use pull_request_target to ensure proper permissions for forks
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Unit-Tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    permissions:  # Add permissions for test reporting
      contents: read
      actions: read
      checks: write

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Step 3: Setup Environment
    - name: Setup Environment
      working-directory: ./Build
      run: ./setup.ps1
      env:
        NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
        NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}
      
    # Step 4: Run Unit Tests
    - name: Run Unit Tests
      working-directory: ./Build
      run: ./RunTests.ps1

    # Step 5: Upload the .trx file as an artifact
    - name: Upload Test Results (.trx)
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: Artifacts/TestResults.trx

    # Step 6: Parse and Display the Test Results
    - name: Report Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: Artifacts/TestResults.trx
        reporter: dotnet-trx
